[project]
name = "pymbusparser"
version = "0.0.0"
description = "Python bindings for m-bus-parser written in Rust"
readme = "README.md"
# name and email
authors = [{name = "Michael Aebli", email = ""}] 
license = "MIT"


[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"